# Read the Docs configuration file for pyproforma
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # Cancel building pull requests when a new commit is pushed
      - git checkout .
    post_install:
      # Install dependencies required for documentation
      - python -m pip install --upgrade pip setuptools wheel

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: docs/requirements.txt

